{{- if not .Values.env.datasource.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unomi.fullname" . }}
  labels:
    {{- include "unomi.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.env.datasource.username | quote }}
  password: {{ .Values.env.datasource.password | quote }}
{{- end }}
