spring:
  application:
    name: unomi-spring-boot-admin

server:
  port: ${SERVER_PORT:9090}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
