package com.unomi.customer.upsert.messaging;

import java.time.Instant;

import com.unomi.customer.upsert.UpsertUserRequest;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Kafka command accepted by the asynchronous customer upsert worker.")
public record UpsertCustomerCommand(
    @Schema(description = "Unique message ID generated by the API layer.")
    String messageId,
    @Schema(description = "Timestamp when the API accepted the user item.")
    Instant acceptedAt,
    @Schema(description = "Whether hook processing should be skipped for this user.")
    boolean skipHook,
    @Schema(description = "Single user payload from the batch upsert request.")
    UpsertUserRequest user
) {
}
